

export const FETCH_DATA_REQUEST="FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS="FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE="FETCH_DATA_FAILURE";


export const ADD_CARD_TO_DETAILS = 'ADD_CARD_TO_DETAILS';